# שלב 1: שימוש ב-Nginx כבסיס
FROM nginx:latest

# שלב 2: העתקת קבצי הפרונטאנד לתוך תיקיית ברירת מחדל של Nginx
COPY . /usr/share/nginx/html

# שלב 3: פתיחת הפורט של Nginx
EXPOSE 80

# אין צורך להפעיל ידנית את Nginx - ברירת המחדל כבר מוגדרת
